# Generated by Django 6.0.5 on 2026-05-10 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Expenses",
            new_name="Expense",
        ),
    ]
